<?php
//Do NOT edit this file

/*Default Config Start*/
$default_mtn = array(
//General
'user' => 'admin',       # User Login 
'pass' => 'admin',       # Pass Login
'showmtnconfig' => false,# Show Configuration at Movie Thumbnailer
'showmtntext' => false,  # Show Text & Output Suffix at Movie Thumbnailer
'c' => '3',             # Columns(1~5)
'r' => '3',             # Rows(1~10)
'w' => '',               # Width(0~2000)
'h' => '100',            # Minimum Height
'T' => '',               # Add text above output image
'o' => 's',              # Output Suffix (i.e : filename_suffix.ext)
'k' => '000000',         # Background Color
'j' => '90',             # Jpeg Quality('80'=Low, '90'=Normal, '100'=Right)
'g' => '1',              # Edge(0~5)
'C' => '',               # Cut movie and thumbnails not more than the specified seconds
'time' => 'min',         # min(minutes), sec(seconds)
'I' => false,            # Individual Shots
'N' => false,            # Save Info
'i' => true,             # Video Info
'Ts' => '10',            # Video Info Size
'Tc' => 'FFFF00',        # Video Info Color
'f' => 'OliJo-Bold.ttf', # Video Info Font
't' => true,             # Time
'tc' => 'FFFF00',        # Time Color
'ts' => '000000',        # Time Shadow Color
'iL' => '4',             # Location Info
'tL' => '2'              # Location Time
);
/*Default Config End*/
?>