<?php
if (!defined('RAPIDLEECH')) { header("Location: ../index.php"); }

if (isset($_POST['setup_save']) && $_POST['setup_save'] == 1) {
	
	$acc_panel = "<?php\r\nif (!defined('RAPIDLEECH')) { require_once('index.html'); exit; }\r\n\r\n#Login Panel\r\n\$user = '".$_POST['user']."';\r\n\$pass = '".$_POST['pass']."';\r\n\r\n### Premium Accounts ###\r\n\$premium_acc = array();\r\n\r\n";
	$acc_pre = array('rapidshare_com', 'netload_in', 'megashare_com', 'gigasize_com', 'shareonline_biz', 'megashares_com', 'vBulletin_acc', 'uploaded_to', 'filefactory_com', 'filedude_com', 'sendspace_com', 'depositfiles_com', 'crocko_com', 'hotfile_com', 'ifile_it', 'fileserve_com', 'filesonic_com', 'uploading_com', 'wupload_com', 'x7', 'freakshare_com', 'oron_com', 'movshare_net', 'veehd_com', 'mediafire_com', 'cramit_in', 'bitshare_com', 'fileserving_com');
	
	reset($acc_pre);
	while (key($acc_pre) !== NULL) {
		if ($_POST['pre_'.current($acc_pre)] && $_POST['pre_'.current($acc_pre).'_user'] && $_POST['pre_'.current($acc_pre).'_pass']) {
			$acc_panel .= "\$premium_acc[\"".current($acc_pre)."\"] = array('user' => '".$_POST['pre_'.current($acc_pre).'_user']."', 'pass' => '".$_POST['pre_'.current($acc_pre).'_pass']."');\r\n";
		}
		else if ($_POST['pre_'.current($acc_pre)] && $_POST['pre_'.current($acc_pre).'_cookie']) {
			$acc_panel .= "//\$premium_acc[\"".current($acc_pre)."\"] = array('user' => '', 'pass' => '');\r\n\$premium_acc[\"".current($acc_pre)."\"] = array('cookie' => '".$_POST['pre_'.current($acc_pre).'_cookie']."');\r\n";
		}
		else if ($_POST['pre_'.current($acc_pre)] && $premium_acc[current($acc_pre)]['user'] && $premium_acc[current($acc_pre)]['pass']) {
			$acc_panel .= "\$premium_acc[\"".current($acc_pre)."\"] = array('user' => '".$premium_acc[current($acc_pre)]['user']."', 'pass' => '".$premium_acc[current($acc_pre)]['pass']."');\r\n";
		}
		else if ($_POST['pre_'.current($acc_pre)] && $premium_acc[current($acc_pre)]['cookie']) {
			$acc_panel .= "//\$premium_acc[\"".current($acc_pre)."\"] = array('user' => '', 'pass' => '');\r\n\$premium_acc[\"".current($acc_pre)."\"] = array('cookie' => '".$premium_acc[current($acc_pre)]['cookie']."');\r\n";
		}
		else {
			$acc_panel .= "//\$premium_acc[\"".current($acc_pre)."\"] = array('user' => '', 'pass' => '');\r\n";
		}
		next($acc_pre);
	}
		
	$acc_panel .= "\r\n### Upload Accounts ###\r\n\$upload_acc = array();\r\n\r\n";
	$acc_up = array('uploaded_to', 'rapidshare_com', 'filesonic_com', 'hotfile_com', 'netload_in', 'uploading_com', 'wupload_com', 'mediafire_com', 'bitshare_com', 'cramit_in');
	
	reset($acc_up);
	while (key($acc_up) !== NULL) {
		if ($_POST['up_'.current($acc_up)] && $_POST['up_'.current($acc_up).'_user'] && $_POST['up_'.current($acc_up).'_pass']) {
			$acc_panel .= "\$upload_acc[\"".current($acc_up)."\"] = array('user' => '".$_POST['up_'.current($acc_up).'_user']."', 'pass' => '".$_POST['up_'.current($acc_up).'_pass']."');\r\n";
		}
		else if ($_POST['up_'.current($acc_up)] && $upload_acc[current($acc_up)]['user'] && $upload_acc[current($acc_up)]['pass']) {
			$acc_panel .= "\$upload_acc[\"".current($acc_up)."\"] = array('user' => '".$upload_acc[current($acc_up)]['user']."', 'pass' => '".$upload_acc[current($acc_up)]['pass']."');\r\n";
		}
		else {
			$acc_panel .= "//\$upload_acc[\"".current($acc_up)."\"] = array('user' => '', 'pass' => '');\r\n";
		}
		next($acc_up);
	}
	
	$acc_panel .= "\r\n#Secret key for cookie encryption\r\n\$secretkey = '".$_POST['secretkey']."';\r\n?>";
	
	ob_start(); ob_get_contents($acc_panel); ob_end_clean();
	if (!@write_file(CONFIG_DIR."accounts.php", $acc_panel, 1)) {
		echo '<div align="center">It was not possible to write the configuration<br />Set permissions of "configs/accounts.php" file to 0777 and try again<br /><b><a href="'.$PHP_SELF.'">Continue to Accounts Panel</a><br />or</b><br /><b><a href="" onclick="window.close()">Close Window</a></b></div>';
	}
	else {
		echo '<center><br /><b class="rev-dev">Configuration saved!<br /><a href="'.$PHP_SELF.'">Continue to Accounts Panel</a><br />or</b><br /><b><a href="" onclick="window.close()">Close Window</a></b></center>';
	}
}
else {
$info = "<br /><center><b><a href=\"\" onclick=\"window.close()\">Close Window</a></b>";
$protected = true;
include_once('login.php');
?>

<form method="post">
<center style="padding-left:600px;"><b><small class="rev-dev">Hi, <?php echo $user; ?> <input type="submit" style="font-size:smaller" name="logout" value="Logout" /></small></b></center>
</form>

<form method="post" enctype="multipart/form-data" name="setup_form" action="<?php echo $PHP_SELF; ?>">
<table border="0" cellspacing="0" align="center">
<tr>
<td align="right">Login : </td><td>User<input type="text" id="user" name="user" size="14" />&nbsp; Pass<input type="text" id="pass" name="pass" size="14" /></td>
</tr>
</table>

<table border="1" cellspacing="0" align="center">
<tr>
<td colspan=4><center><b style="font-size:13px">Premium Accounts</b></center>
</td>
<tr>
<tr>
<td align="right"><label for="pre_rapidshare_com">RapidShare.com</label><input type="checkbox" id="pre_rapidshare_com" name="pre_rapidshare_com" onclick="document.getElementById('showpre_rapidshare_com').style.display=this.checked?'none':'<?php if($premium_acc["rapidshare_com"]){echo 'none';} ?>';document.getElementById('optpre_rapidshare_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_rapidshare_com"><?php if($premium_acc["rapidshare_com"]['user'] && $premium_acc["rapidshare_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else if($premium_acc["rapidshare_com"]['cookie']) { echo "<small class=\"rev-dev\"><b> &nbsp; Cookie embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account/Cookie not embedded</b></small>"; }?></span><span id="optpre_rapidshare_com" style="display:none">User:<input type="text" name="pre_rapidshare_com_user" size="16" />&nbsp; Pass:<input type="password" name="pre_rapidshare_com_pass" size="16" /> or<br />Cookie:<input type="text" name="pre_rapidshare_com_cookie" size="42" /></span></td>
<td align="right"><label for="pre_netload_in">NetLoad.in</label><input type="checkbox" id="pre_netload_in" name="pre_netload_in" onclick="document.getElementById('showpre_netload_in').style.display=this.checked?'none':'<?php if($premium_acc["netload_in"]){echo 'none';} ?>';document.getElementById('optpre_netload_in').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_netload_in"><?php if($premium_acc["netload_in"]['user'] && $premium_acc["netload_in"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_netload_in" style="display:none">ID:<input name="pre_netload_in_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_netload_in_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_megashare_com">MegaShare.com</label><input type="checkbox" id="pre_megashare_com" name="pre_megashare_com" onclick="document.getElementById('showpre_megashare_com').style.display=this.checked?'none':'<?php if($premium_acc["megashare_com"]){echo 'none';} ?>';document.getElementById('optpre_megashare_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_megashare_com"><?php if($premium_acc["megashare_com"]['user'] && $premium_acc["megashare_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_megashare_com" style="display:none">User:<input name="pre_megashare_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_megashare_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_gigasize_com">GigaSize.com</label><input type="checkbox" id="pre_gigasize_com" name="pre_gigasize_com" onclick="document.getElementById('showpre_gigasize_com').style.display=this.checked?'none':'<?php if($premium_acc["gigasize_com"]){echo 'none';} ?>';document.getElementById('optpre_gigasize_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_gigasize_com"><?php if($premium_acc["gigasize_com"]['user'] && $premium_acc["gigasize_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_gigasize_com" style="display:none">Email:<input name="pre_gigasize_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_gigasize_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_shareonline_biz">ShareOnline.biz</label><input type="checkbox" id="pre_shareonline_biz" name="pre_shareonline_biz" onclick="document.getElementById('showpre_shareonline_biz').style.display=this.checked?'none':'<?php if($premium_acc["shareonline_biz"]){echo 'none';} ?>';document.getElementById('optpre_shareonline_biz').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_shareonline_biz"><?php if($premium_acc["shareonline_biz"]['user'] && $premium_acc["shareonline_biz"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_shareonline_biz" style="display:none">User:<input name="pre_shareonline_biz_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_shareonline_biz_pass" size="16" /></span></td>
<td align="right"><label for="pre_megashares_com">MegaShares.com</label><input type="checkbox" id="pre_megashares_com" name="pre_megashares_com" onclick="document.getElementById('showpre_megashares_com').style.display=this.checked?'none':'<?php if($premium_acc["megashares_com"]){echo 'none';} ?>';document.getElementById('optpre_megashares_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_megashares_com"><?php if($premium_acc["megashares_com"]['user'] && $premium_acc["megashares_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_megashares_com" style="display:none">User:<input name="pre_megashares_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_megashares_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_vBulletin_acc">vBulletin acc</label><input type="checkbox" id="pre_vBulletin_acc" name="pre_vBulletin_acc" onclick="document.getElementById('showpre_vBulletin_acc').style.display=this.checked?'none':'<?php if($premium_acc["vBulletin_acc"]){echo 'none';} ?>';document.getElementById('optpre_vBulletin_acc').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_vBulletin_acc"><?php if($premium_acc["vBulletin_acc"]['user'] && $premium_acc["vBulletin_acc"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_vBulletin_acc" style="display:none">User:<input name="pre_vBulletin_acc_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_vBulletin_acc_pass" size="16" /></span></td>
<td align="right"><label for="pre_uploaded_to">UpLoaded.to</label><input type="checkbox" id="pre_uploaded_to" name="pre_uploaded_to" onclick="document.getElementById('showpre_uploaded_to').style.display=this.checked?'none':'<?php if($premium_acc["uploaded_to"]){echo 'none';} ?>';document.getElementById('optpre_uploaded_to').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_uploaded_to"><?php if($premium_acc["uploaded_to"]['user'] && $premium_acc["uploaded_to"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else if($premium_acc["uploaded_to"]['cookie']) { echo "<small class=\"rev-dev\"><b> &nbsp; Cookie embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account/Cookie not embedded</b></small>"; }?></span><span id="optpre_uploaded_to" style="display:none">ID:<input type="text" name="pre_uploaded_to_user" size="16" />&nbsp; Pass:<input type="password" name="pre_uploaded_to_pass" size="16" /> or<br />Cookie:<input type="text" name="pre_uploaded_to_cookie" size="42" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_filefactory_com">FileFactory.com</label><input type="checkbox" id="pre_filefactory_com" name="pre_filefactory_com" onclick="document.getElementById('showpre_filefactory_com').style.display=this.checked?'none':'<?php if($premium_acc["filefactory_com"]){echo 'none';} ?>';document.getElementById('optpre_filefactory_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_filefactory_com"><?php if($premium_acc["filefactory_com"]['user'] && $premium_acc["filefactory_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_filefactory_com" style="display:none">Email:<input name="pre_filefactory_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_filefactory_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_filedude_com">FileDude.com</label><input type="checkbox" id="pre_filedude_com" name="pre_filedude_com" onclick="document.getElementById('showpre_filedude_com').style.display=this.checked?'none':'<?php if($premium_acc["filedude_com"]){echo 'none';} ?>';document.getElementById('optpre_filedude_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_filedude_com"><?php if($premium_acc["filedude_com"]['user'] && $premium_acc["filedude_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_filedude_com" style="display:none">User:<input name="pre_filedude_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_filedude_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_sendspace_com">SendSpace.com</label><input type="checkbox" id="pre_sendspace_com" name="pre_sendspace_com" onclick="document.getElementById('showpre_sendspace_com').style.display=this.checked?'none':'<?php if($premium_acc["sendspace_com"]){echo 'none';} ?>';document.getElementById('optpre_sendspace_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_sendspace_com"><?php if($premium_acc["sendspace_com"]['user'] && $premium_acc["sendspace_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_sendspace_com" style="display:none">User:<input name="pre_sendspace_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_sendspace_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_depositfiles_com">DepositFiles.com</label><input type="checkbox" id="pre_depositfiles_com" name="pre_depositfiles_com" onclick="document.getElementById('showpre_depositfiles_com').style.display=this.checked?'none':'<?php if($premium_acc["depositfiles_com"]){echo 'none';} ?>';document.getElementById('optpre_depositfiles_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_depositfiles_com"><?php if($premium_acc["depositfiles_com"]['user'] && $premium_acc["depositfiles_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else if($premium_acc["depositfiles_com"]['cookie']) { echo "<small class=\"rev-dev\"><b> &nbsp; Cookie embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account/Cookie not embedded</b></small>"; }?></span><span id="optpre_depositfiles_com" style="display:none">Login:<input type="text" name="pre_depositfiles_com_user" size="16" />&nbsp; Pass:<input type="password" name="pre_depositfiles_com_pass" size="16" /> or<br />Cookie:<input type="text" name="pre_depositfiles_com_cookie" size="42" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_crocko_com">Crocko.com</label><input type="checkbox" id="pre_crocko_com" name="pre_crocko_com" onclick="document.getElementById('showpre_crocko_com').style.display=this.checked?'none':'<?php if($premium_acc["crocko_com"]){echo 'none';} ?>';document.getElementById('optpre_crocko_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_crocko_com"><?php if($premium_acc["crocko_com"]['user'] && $premium_acc["crocko_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_crocko_com" style="display:none">Login:<input name="pre_crocko_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_crocko_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_hotfile_com">HotFile.com</label><input type="checkbox" id="pre_hotfile_com" name="pre_hotfile_com" onclick="document.getElementById('showpre_hotfile_com').style.display=this.checked?'none':'<?php if($premium_acc["hotfile_com"]){echo 'none';} ?>';document.getElementById('optpre_hotfile_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_hotfile_com"><?php if($premium_acc["hotfile_com"]['user'] && $premium_acc["hotfile_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else if($premium_acc["hotfile_com"]['cookie']) { echo "<small class=\"rev-dev\"><b> &nbsp; Cookie embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account/Cookie not embedded</b></small>"; }?></span><span id="optpre_hotfile_com" style="display:none">User:<input type="text" name="pre_hotfile_com_user" size="16" />&nbsp; Pass:<input type="password" name="pre_hotfile_com_pass" size="16" /> or<br />Cookie:<input type="text" name="pre_hotfile_com_cookie" size="42" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_ifile_it">Ifile.it</label><input type="checkbox" id="pre_ifile_it" name="pre_ifile_it" onclick="document.getElementById('showpre_ifile_it').style.display=this.checked?'none':'<?php if($premium_acc["ifile_it"]){echo 'none';} ?>';document.getElementById('optpre_ifile_it').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_ifile_it"><?php if($premium_acc["ifile_it"]['user'] && $premium_acc["ifile_it"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_ifile_it" style="display:none">User:<input name="pre_ifile_it_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_ifile_it_pass" size="16" /></span></td>
<td align="right"><label for="pre_fileserve_com">FileServe.com</label><input type="checkbox" id="pre_fileserve_com" name="pre_fileserve_com" onclick="document.getElementById('showpre_fileserve_com').style.display=this.checked?'none':'<?php if($premium_acc["fileserve_com"]){echo 'none';} ?>';document.getElementById('optpre_fileserve_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_fileserve_com"><?php if($premium_acc["fileserve_com"]['user'] && $premium_acc["fileserve_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_fileserve_com" style="display:none">User:<input name="pre_fileserve_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_fileserve_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_filesonic_com">FileSonic.com</label><input type="checkbox" id="pre_filesonic_com" name="pre_filesonic_com" onclick="document.getElementById('showpre_filesonic_com').style.display=this.checked?'none':'<?php if($premium_acc["filesonic_com"]){echo 'none';} ?>';document.getElementById('optpre_filesonic_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_filesonic_com"><?php if($premium_acc["filesonic_com"]['user'] && $premium_acc["filesonic_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_filesonic_com" style="display:none">User:<input name="pre_filesonic_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_filesonic_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_uploading_com">Uploading.com</label><input type="checkbox" id="pre_uploading_com" name="pre_uploading_com" onclick="document.getElementById('showpre_uploading_com').style.display=this.checked?'none':'<?php if($premium_acc["uploading_com"]){echo 'none';} ?>';document.getElementById('optpre_uploading_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_uploading_com"><?php if($premium_acc["uploading_com"]['user'] && $premium_acc["uploading_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else if($premium_acc["uploading_com"]['cookie']) { echo "<small class=\"rev-dev\"><b> &nbsp; Cookie embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account/Cookie not embedded</b></small>"; }?></span><span id="optpre_uploading_com" style="display:none">Email:<input type="text" name="pre_uploading_com_user" size="16" />&nbsp; Pass:<input type="password" name="pre_uploading_com_pass" size="16" /> or<br />Cookie:<input type="text" name="pre_uploading_com_cookie" size="42" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_wupload_com">Wupload.com</label><input type="checkbox" id="pre_wupload_com" name="pre_wupload_com" onclick="document.getElementById('showpre_wupload_com').style.display=this.checked?'none':'<?php if($premium_acc["wupload_com"]){echo 'none';} ?>';document.getElementById('optpre_wupload_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_wupload_com"><?php if($premium_acc["wupload_com"]['user'] && $premium_acc["wupload_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_wupload_com" style="display:none">User:<input name="pre_wupload_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_wupload_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_x7">x7</label><input type="checkbox" id="pre_x7" name="pre_x7" onclick="document.getElementById('showpre_x7').style.display=this.checked?'none':'<?php if($premium_acc["x7"]){echo 'none';} ?>';document.getElementById('optpre_x7').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_x7"><?php if($premium_acc["x7"]['user'] && $premium_acc["x7"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_x7" style="display:none">User:<input name="pre_x7_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_x7_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_freakshare_com">FreakShare.com</label><input type="checkbox" id="pre_freakshare_com" name="pre_freakshare_com" onclick="document.getElementById('showpre_freakshare_com').style.display=this.checked?'none':'<?php if($premium_acc["freakshare_com"]){echo 'none';} ?>';document.getElementById('optpre_freakshare_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_freakshare_com"><?php if($premium_acc["freakshare_com"]['user'] && $premium_acc["freakshare_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_freakshare_com" style="display:none">User:<input name="pre_freakshare_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_freakshare_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_oron_com">Oron.com</label><input type="checkbox" id="pre_oron_com" name="pre_oron_com" onclick="document.getElementById('showpre_oron_com').style.display=this.checked?'none':'<?php if($premium_acc["oron_com"]){echo 'none';} ?>';document.getElementById('optpre_oron_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_oron_com"><?php if($premium_acc["oron_com"]['user'] && $premium_acc["oron_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_oron_com" style="display:none">User:<input name="pre_oron_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_oron_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_movshare_net">MovShare.net</label><input type="checkbox" id="pre_movshare_net" name="pre_movshare_net" onclick="document.getElementById('showpre_movshare_net').style.display=this.checked?'none':'<?php if($premium_acc["movshare_net"]){echo 'none';} ?>';document.getElementById('optpre_movshare_net').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_movshare_net"><?php if($premium_acc["movshare_net"]['user'] && $premium_acc["movshare_net"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_movshare_net" style="display:none">User:<input name="pre_movshare_net_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_movshare_net_pass" size="16" /></span></td>
<td align="right"><label for="pre_veehd_com">VeeHD.com</label><input type="checkbox" id="pre_veehd_com" name="pre_veehd_com" onclick="document.getElementById('showpre_veehd_com').style.display=this.checked?'none':'<?php if($premium_acc["veehd_com"]){echo 'none';} ?>';document.getElementById('optpre_veehd_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_veehd_com"><?php if($premium_acc["veehd_com"]['user'] && $premium_acc["veehd_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_veehd_com" style="display:none">User:<input name="pre_veehd_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_veehd_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_mediafire_com">MediaFire.com</label><input type="checkbox" id="pre_mediafire_com" name="pre_mediafire_com" onclick="document.getElementById('showpre_mediafire_com').style.display=this.checked?'none':'<?php if($premium_acc["mediafire_com"]){echo 'none';} ?>';document.getElementById('optpre_mediafire_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_mediafire_com"><?php if($premium_acc["mediafire_com"]['user'] && $premium_acc["mediafire_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_mediafire_com" style="display:none">Email:<input name="pre_mediafire_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_mediafire_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_cramit_in">Cramit.in</label><input type="checkbox" id="pre_cramit_in" name="pre_cramit_in" onclick="document.getElementById('showpre_cramit_in').style.display=this.checked?'none':'<?php if($premium_acc["cramit_in"]){echo 'none';} ?>';document.getElementById('optpre_cramit_in').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_cramit_in"><?php if($premium_acc["cramit_in"]['user'] && $premium_acc["cramit_in"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_cramit_in" style="display:none">Login:<input name="pre_cramit_in_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_cramit_in_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="pre_bitshare_com">BitShare.com</label><input type="checkbox" id="pre_bitshare_com" name="pre_bitshare_com" onclick="document.getElementById('showpre_bitshare_com').style.display=this.checked?'none':'<?php if($premium_acc["bitshare_com"]){echo 'none';} ?>';document.getElementById('optpre_bitshare_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_bitshare_com"><?php if($premium_acc["bitshare_com"]['user'] && $premium_acc["bitshare_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_bitshare_com" style="display:none">User:<input name="pre_bitshare_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_bitshare_com_pass" size="16" /></span></td>
<td align="right"><label for="pre_fileserving_com">FileServing.com</label><input type="checkbox" id="pre_fileserving_com" name="pre_fileserving_com" onclick="document.getElementById('showpre_fileserving_com').style.display=this.checked?'none':'<?php if($premium_acc["fileserving_com"]){echo 'none';} ?>';document.getElementById('optpre_fileserving_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showpre_fileserving_com"><?php if($premium_acc["fileserving_com"]['user'] && $premium_acc["fileserving_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optpre_fileserving_com" style="display:none">Email:<input name="pre_fileserving_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="pre_fileserving_com_pass" size="16" /></span></td>
</tr>

<tr>
<td></td><td style="padding-left:313px;">&nbsp;</td>
<td></td><td style="padding-left:313px;">&nbsp;</td>
</tr>
</table>

<table border="1" cellspacing="0" align="center">
<tr>
<td colspan=4 ><center><b style="font-size:13px">Upload Accounts</b></center>
</td>
<tr>

<tr>
<td align="right"><label for="up_uploaded_to">UpLoaded.to</label><input type="checkbox" id="up_uploaded_to" name="up_uploaded_to" onclick="document.getElementById('showup_uploaded_to').style.display=this.checked?'none':'<?php if($upload_acc["uploaded_to"]){echo 'none';} ?>';document.getElementById('optup_uploaded_to').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_uploaded_to"><?php if($upload_acc["uploaded_to"]['user'] && $upload_acc["uploaded_to"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_uploaded_to" style="display:none">ID:<input name="up_uploaded_to_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_uploaded_to_pass" size="16" /></span></td>
<td align="right"><label for="up_rapidshare_com">RapidShare.com</label><input type="checkbox" id="up_rapidshare_com" name="up_rapidshare_com" onclick="document.getElementById('showup_rapidshare_com').style.display=this.checked?'none':'<?php if($upload_acc["rapidshare_com"]){echo 'none';} ?>';document.getElementById('optup_rapidshare_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_rapidshare_com"><?php if($upload_acc["rapidshare_com"]['user'] && $upload_acc["rapidshare_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_rapidshare_com" style="display:none">User:<input name="up_rapidshare_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_rapidshare_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="up_filesonic_com">FileSonic.com</label><input type="checkbox" id="up_filesonic_com" name="up_filesonic_com" onclick="document.getElementById('showup_filesonic_com').style.display=this.checked?'none':'<?php if($upload_acc["filesonic_com"]){echo 'none';} ?>';document.getElementById('optup_filesonic_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_filesonic_com"><?php if($upload_acc["filesonic_com"]['user'] && $upload_acc["filesonic_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_filesonic_com" style="display:none">User:<input name="up_filesonic_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_filesonic_com_pass" size="16" /></span></td>
<td align="right"><label for="up_hotfile_com">HotFile.com</label><input type="checkbox" id="up_hotfile_com" name="up_hotfile_com" onclick="document.getElementById('showup_hotfile_com').style.display=this.checked?'none':'<?php if($upload_acc["hotfile_com"]){echo 'none';} ?>';document.getElementById('optup_hotfile_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_hotfile_com"><?php if($upload_acc["hotfile_com"]['user'] && $upload_acc["hotfile_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_hotfile_com" style="display:none">User:<input name="up_hotfile_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_hotfile_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="up_netload_in">NetLoad.in</label><input type="checkbox" id="up_netload_in" name="up_netload_in" onclick="document.getElementById('showup_netload_in').style.display=this.checked?'none':'<?php if($upload_acc["netload_in"]){echo 'none';} ?>';document.getElementById('optup_netload_in').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_netload_in"><?php if($upload_acc["netload_in"]['user'] && $upload_acc["netload_in"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_netload_in" style="display:none">ID:<input name="up_netload_in_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_netload_in_pass" size="16" /></span></td>
<td align="right"><label for="up_uploading_com">UpLoading.com</label><input type="checkbox" id="up_uploading_com" name="up_uploading_com" onclick="document.getElementById('showup_uploading_com').style.display=this.checked?'none':'<?php if($upload_acc["uploading_com"]){echo 'none';} ?>';document.getElementById('optup_uploading_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_uploading_com"><?php if($upload_acc["uploading_com"]['user'] && $upload_acc["uploading_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_uploading_com" style="display:none">Email:<input name="up_uploading_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_uploading_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="up_wupload_com">Wupload.com</label><input type="checkbox" id="up_wupload_com" name="up_wupload_com" onclick="document.getElementById('showup_wupload_com').style.display=this.checked?'none':'<?php if($upload_acc["wupload_com"]){echo 'none';} ?>';document.getElementById('optup_wupload_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_wupload_com"><?php if($upload_acc["wupload_com"]['user'] && $upload_acc["wupload_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_wupload_com" style="display:none">User:<input name="up_wupload_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_wupload_com_pass" size="16" /></span></td>
<td align="right"><label for="up_mediafire_com">MediaFire.com</label><input type="checkbox" id="up_mediafire_com" name="up_mediafire_com" onclick="document.getElementById('showup_mediafire_com').style.display=this.checked?'none':'<?php if($upload_acc["mediafire_com"]){echo 'none';} ?>';document.getElementById('optup_mediafire_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_mediafire_com"><?php if($upload_acc["mediafire_com"]['user'] && $upload_acc["mediafire_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_mediafire_com" style="display:none">Email:<input name="up_mediafire_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_mediafire_com_pass" size="16" /></span></td>
</tr>

<tr>
<td align="right"><label for="up_bitshare_com">BitShare.com</label><input type="checkbox" id="up_bitshare_com" name="up_bitshare_com" onclick="document.getElementById('showup_bitshare_com').style.display=this.checked?'none':'<?php if($upload_acc["bitshare_com"]){echo 'none';} ?>';document.getElementById('optup_bitshare_com').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_bitshare_com"><?php if($upload_acc["bitshare_com"]['user'] && $upload_acc["bitshare_com"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_bitshare_com" style="display:none">User:<input name="up_bitshare_com_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_bitshare_com_pass" size="16" /></span></td>
<td align="right"><label for="up_cramit_in">Cramit.in</label><input type="checkbox" id="up_cramit_in" name="up_cramit_in" onclick="document.getElementById('showup_cramit_in').style.display=this.checked?'none':'<?php if($upload_acc["cramit_in"]){echo 'none';} ?>';document.getElementById('optup_cramit_in').style.display=this.checked?'':'none';" value="true" /></td><td><span id="showup_cramit_in"><?php if($upload_acc["cramit_in"]['user'] && $upload_acc["cramit_in"]['pass']) { echo "<small class=\"rev-dev\"><b> &nbsp; Account embedded</b></small>"; } else { echo "<small class=\"rev-dev\"><b> &nbsp; Account not embedded</b></small>"; }?></span><span id="optup_cramit_in" style="display:none">Login:<input name="up_cramit_in_user" type="text" size="16" />&nbsp; Pass:<input type="password" name="up_cramit_in_pass" size="16" /></span></td>
</tr>

<tr>
<td></td><td style="padding-left:300px;">&nbsp;</td>
<td></td><td style="padding-left:300px;">&nbsp;</td>
</tr>

<tr>
<td align="center" colspan=4><span onMouseOver="document.getElementById('text_secretkey').style.display='block'" onMouseOut="document.getElementById('text_secretkey').style.display='none'" style="cursor:help">Secretkey</span> : <input name="secretkey" type="text" id="secretkey" size="56" maxlength="56" /></td>
</tr>
</table>
<center>
<input type="hidden" value="1" name="setup_save" /><input type="button" value="Save" id="save" name="save" disabled="disabled" />
<span id="text_secretkey" style="display:none">#Secret key for cookie encryption<br />#Make up a random one to protect your premium cookies (max length: 56). Example: $secretkey = 'UijSY5wjP1Ii'; - DO NOT use this example $secretkey, or your premium accounts/cookies could be stolen!!<br />#IF THIS IS NOT SET BEFORE YOU USE PREMIUM SERVICES, YOU WILL BE WARNED BY THE RAPIDLEECH SCRIPT. OTHERWISE YOUR PREMIUM ACCOUNTS AND/OR COOKIES COULD BE COMPROMISED!</span>
</center>
</form>

<?php
}
?>