<?php
 if (!defined('RAPIDLEECH')) { require_once('index.html'); exit; }

$options = array (
  'download_dir' => 'videos/',
  'download_dir_is_changeable' => false,
  'delete_delay' => 300,
  'rename_prefix' => '',
  'rename_suffix' => '',
  'rename_underscore' => true,
  'bw_save' => true,
  'file_size_limit' => 500,
  'auto_download_disable' => true,
  'auto_upload_disable' => true,
  'notes_disable' => true,
  'upload_html_disable' => false,
  'myuploads_disable' => true,
  'login' => false,
  'users' => 
  array (
    '123' => '123',
  ),
  'login_cgi' => false,
  'template_used' => 'RapidTube',
  'default_language' => 'en',
  'show_all' => false,
  'server_info' => false,
  'ajax_refresh' => true,
  'new_window' => false,
  'new_window_js' => true,
  'flist_sort' => false,
  'flist_h_fixed' => false,
  'disable_actions' => true,
  'disable_deleting' => true,
  'disable_delete' => true,
  'disable_rename' => true,
  'disable_mass_rename' => true,
  'disable_mass_email' => true,
  'disable_email' => true,
  'disable_ftp' => true,
  'disable_upload' => true,
  'disable_merge' => true,
  'disable_split' => true,
  'disable_archive_compression' => false,
  'disable_tar' => true,
  'disable_zip' => true,
  'disable_unzip' => true,
  'disable_rar' => true,
  'disable_unrar' => true,
  'disable_md5' => false,
  'disable_md5_change' => true,
  'disable_list' => true,
  '2gb_fix' => true,
  'forbidden_filetypes' => array('.htaccess', '.htpasswd', '.php', '.php3', '.php4', '.php5', '.phtml', '.asp', '.aspx', '.cgi', '.jpg', '.bmp', '.gif', '.mp3', '.fla', '.zip', '.rar', '.tar.gz', '.tar', '.exe', '.css'),
  'forbidden_filetypes_block' => true,
  'rename_these_filetypes_to' => '.xxx',
  'check_these_before_unzipping' => true,
  'no_cache' => true,
  'images_via_php' => false,
  'use_curl' => true,
  'redir' => true,
  'fgc' => 0,
); 

require_once('site_checker.php');
require_once('accounts.php');
?>